services:
  app:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: app
    hostname: app
    restart: on-failure
    env_file:
      - ../build/.env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    networks:
      - proxy_net
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST: "127.0.0.1"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "db"
    networks:
      - proxy_net
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres:

networks:
  proxy_net:
    name: proxy_net
    driver: bridge
